export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_TOKEN = "UPDATE_TOKEN";
export const UPDATE_LOGIN = "UPDATE_LOGIN";
export const UPDATE_PERSONAL = "UPDATE_PERSONAL";